# ╔══════════════════════════════════════════════════════════════════════╗
# ║  MARK4K — AI-Powered Academic Assistant                              ║
# ║  Built for DigitalOcean Gradient™ AI Hackathon                      ║
# ║  Powered by: DigitalOcean Gradient AI Agent (Qwen3 32B)             ║
# ╚══════════════════════════════════════════════════════════════════════╝

import os, io, re, zipfile, smtplib
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from flask import Flask, request, jsonify, session, send_file, render_template_string

# ── Optional deps (pip install fpdf2 pypdf) ────────────────────────────
try:
    from fpdf import FPDF
    PDF_ENABLED = True
except ImportError:
    PDF_ENABLED = False

try:
    import pypdf
    PYPDF_ENABLED = True
except ImportError:
    PYPDF_ENABLED = False

# ══════════════════════════════════════════════════════════════════════
app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "mark4k-hackathon-2025")

# ── DigitalOcean Gradient AI Agent Endpoint ────────────────────────────
AGENT_URL = "https://cjkgjyoo5oezhc77dzx2dmbx.agents.do-ai.run/api/v1/chat/completions"
AGENT_KEY = "EVr9Lb0a2MdMY3F7nGCRmC407REoRrOt"
AGENT_ENDPOINT = "https://cjkgjyoo5oezhc77dzx2dmbx.agents.do-ai.run/api/v1/chat/completions"
AGENT_ACCESS_KEY = "EVr9Lb0a2MdMY3F7nGCRmC407REoRrOt"  # paste your key here

# Keep last N turns to avoid 4KB Flask session cookie overflow
MAX_HISTORY = 12

# ══════════════════════════════════════════════════════════════════════
#  MODE PROMPTS — steer the agent based on selected feature mode
# ══════════════════════════════════════════════════════════════════════
MODE_PROMPTS = {
    "chat": "",
    "path": (
        "[EDUCATION PATH MODE] Advise the student on academic progression "
        "(High School to BSc, BSc to Masters, Masters to PhD, PhD to Professor). "
        "Recommend specific courses, universities, and scholarships. Be practical."
    ),
    "pdf": (
        "[DOCUMENT ANALYSIS MODE] Analyze the uploaded document. "
        "Summarize key points, identify assignment requirements, suggest an approach, "
        "and flag any important deadlines or criteria."
    ),
    "code": (
        "[CODE GENERATION MODE] Generate clean, well-commented code using proper "
        "fenced code blocks (```python, ```html, ```bash etc). "
        "For Flask/Django apps include all needed files (app.py, requirements.txt, templates). "
        "Briefly explain the file structure after the code."
    ),
    "email": (
        "[EMAIL MODE] Draft a professional academic email with a clear Subject line, "
        "greeting, body paragraphs, and closing. Keep it polite and concise."
    ),
}

# ══════════════════════════════════════════════════════════════════════
#  HELPERS
# ══════════════════════════════════════════════════════════════════════

def call_agent(messages):
    """Send conversation history to the DigitalOcean Gradient AI agent."""
    resp = requests.post(
        AGENT_URL,
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {AGENT_KEY}"},
        json={"messages": messages},
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]


def extract_code_blocks(text):
    """Parse all fenced code blocks from markdown. Returns list of {lang, code}."""
    matches = re.findall(r"```(\w+)?\n(.*?)```", text, re.DOTALL)
    return [{"lang": m[0] or "txt", "code": m[1].strip()} for m in matches]


def build_zip(code_blocks):
    """Package code blocks into an in-memory ZIP. Returns BytesIO."""
    lang_to_file = {
        "python": "app.py", "py": "app.py",
        "html": "templates/index.html",
        "css": "static/style.css",
        "javascript": "static/script.js", "js": "static/script.js",
        "bash": "setup.sh", "sh": "setup.sh",
        "json": "config.json",
    }
    buf = io.BytesIO()
    seen = {}
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.md",
            "# Mark4k Generated Project\n\nGenerated by Mark4k — "
            "DigitalOcean Gradient AI Academic Assistant.\n\n"
            "## Setup\n```\npip install -r requirements.txt\npython app.py\n```\n")
        for i, block in enumerate(code_blocks):
            lang  = block["lang"].lower()
            fname = lang_to_file.get(lang, f"file_{i}.{lang}")
            if fname in seen:
                seen[fname] += 1
                base, ext = os.path.splitext(fname)
                fname = f"{base}_{seen[fname]}{ext}"
            else:
                seen[fname] = 0
            zf.writestr(fname, block["code"])
    buf.seek(0)
    return buf


def generate_pdf(title, content):
    """Render a branded Mark4k PDF document. Returns BytesIO."""
    pdf = FPDF()
    pdf.add_page()
    # Header
    pdf.set_fill_color(9, 17, 31)
    pdf.rect(0, 0, 210, 38, "F")
    pdf.set_text_color(201, 168, 76)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_xy(12, 9)
    pdf.cell(0, 10, "MARK4K")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(160, 180, 200)
    pdf.set_xy(12, 22)
    pdf.cell(0, 8, "Academic Assistant  |  Powered by DigitalOcean Gradient AI")
    # Title
    pdf.set_xy(12, 46)
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 15)
    pdf.multi_cell(186, 9, title)
    # Divider
    pdf.set_draw_color(201, 168, 76)
    pdf.set_line_width(0.6)
    y = pdf.get_y() + 4
    pdf.line(12, y, 198, y)
    pdf.ln(8)
    # Body
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(35, 35, 35)
    clean = re.sub(r"\*\*(.+?)\*\*", r"\1", content)
    clean = re.sub(r"\*(.+?)\*", r"\1", clean)
    clean = re.sub(r"#{1,6}\s+", "", clean)
    clean = re.sub(r"```[\s\S]*?```", "[code block — download ZIP for full code]", clean)
    for line in clean.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue
        try:
            pdf.multi_cell(186, 7, line)
        except Exception:
            pass
    # Footer
    pdf.set_y(-18)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, "Generated by Mark4k  |  DigitalOcean Gradient AI Hackathon", align="C")
    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf


# ══════════════════════════════════════════════════════════════════════
#  EMBEDDED SINGLE-PAGE FRONTEND
#  Design: Dark Academic — deep navy + gold accents
#  Fonts: Playfair Display (headings) + DM Sans (body) + JetBrains Mono (code)
# ══════════════════════════════════════════════════════════════════════
HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Mark4k — Academic Assistant</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:ital,wght@0,300;0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#08101e;--s1:#0d1b2e;--s2:#122236;--s3:#172b42;
  --bd:#1c344f;--gold:#c9a84c;--gdim:#7a5f28;--gg:rgba(201,168,76,.13);
  --tx:#d8e4f0;--txd:#6b85a0;--green:#22c55e;--red:#ef4444;
}
html,body{height:100%;overflow:hidden}
body{font-family:'DM Sans',sans-serif;background:var(--bg);color:var(--tx);display:flex;height:100vh}

/* ── Sidebar ─────────────────────────────── */
.sb{width:230px;background:var(--s1);border-right:1px solid var(--bd);display:flex;flex-direction:column;flex-shrink:0}
.logo{padding:22px 18px 16px;border-bottom:1px solid var(--bd)}
.logo-m{font-family:'Playfair Display',serif;font-size:21px;color:var(--gold);letter-spacing:3px}
.logo-s{font-size:9px;color:var(--txd);letter-spacing:1.8px;text-transform:uppercase;margin-top:3px}
.nav{padding:12px 10px;flex:1}
.ns{font-size:9px;text-transform:uppercase;letter-spacing:1.8px;color:var(--txd);padding:0 8px;margin:12px 0 5px}
.ni{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:8px;cursor:pointer;transition:all .16s;font-size:13px;font-weight:500;color:var(--txd);margin-bottom:2px;position:relative}
.ni:hover{background:var(--s2);color:var(--tx)}
.ni.on{background:linear-gradient(120deg,#0d2a45,#142d46);color:var(--gold);border:1px solid rgba(201,168,76,.2)}
.ni.on::before{content:'';position:absolute;left:0;top:20%;height:60%;width:3px;background:var(--gold);border-radius:0 3px 3px 0}
.sf{padding:14px 16px;border-top:1px solid var(--bd);font-size:10px;color:var(--txd)}
.do-p{display:inline-flex;align-items:center;gap:5px;background:rgba(0,105,255,.15);border:1px solid rgba(0,105,255,.3);color:#60a5fa;font-size:10px;font-weight:600;padding:3px 9px;border-radius:20px}

/* ── Main ────────────────────────────────── */
.main{flex:1;display:flex;flex-direction:column;overflow:hidden}
.topbar{height:52px;background:var(--s1);border-bottom:1px solid var(--bd);display:flex;align-items:center;justify-content:space-between;padding:0 18px;flex-shrink:0}
.tl{display:flex;align-items:center;gap:9px}
.ttl{font-size:14px;font-weight:600}
.mbadge{font-size:10px;color:var(--gold);background:var(--gg);border:1px solid rgba(201,168,76,.25);padding:2px 9px;border-radius:20px}
.tr{display:flex;gap:7px}
.ib{width:32px;height:32px;border-radius:7px;border:1px solid var(--bd);background:var(--s2);color:var(--txd);font-size:14px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all .16s}
.ib:hover{border-color:var(--gdim);color:var(--gold)}

/* ── Chat ────────────────────────────────── */
.chat{flex:1;overflow-y:auto;padding:22px 18px;display:flex;flex-direction:column;gap:14px;scroll-behavior:smooth}
.chat::-webkit-scrollbar{width:3px}
.chat::-webkit-scrollbar-thumb{background:var(--bd);border-radius:2px}

/* Welcome */
.wl{text-align:center;padding:50px 20px 30px;animation:fu .5s ease both}
.wg{font-size:44px;margin-bottom:14px;display:block}
.wl h2{font-family:'Playfair Display',serif;font-size:24px;color:var(--gold);margin-bottom:8px}
.wl p{color:var(--txd);font-size:13.5px;max-width:380px;margin:0 auto 22px;line-height:1.65}
.chips{display:flex;flex-wrap:wrap;gap:7px;justify-content:center;max-width:520px;margin:0 auto}
.chip{background:var(--s2);border:1px solid var(--bd);color:var(--txd);font-size:12px;padding:6px 13px;border-radius:20px;cursor:pointer;transition:all .16s;font-family:'DM Sans',sans-serif}
.chip:hover{border-color:var(--gdim);color:var(--gold);background:var(--gg)}

/* Messages */
.msg{display:flex;gap:9px;animation:fu .25s ease both;max-width:100%}
.msg.u{flex-direction:row-reverse}
.av{width:30px;height:30px;border-radius:7px;display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0}
.av.a{background:linear-gradient(135deg,#0c2640,#1a3550);border:1px solid var(--gdim)}
.av.u{background:linear-gradient(135deg,#162b44,#1e3850)}
.bub{max-width:72%;padding:11px 15px;border-radius:11px;font-size:13.5px;line-height:1.65}
.msg.a .bub{background:var(--s2);border:1px solid var(--bd);border-top-left-radius:3px;color:var(--tx)}
.msg.u .bub{background:linear-gradient(135deg,#0e2840,#172f4a);border:1px solid var(--bd);border-top-right-radius:3px;color:var(--tx)}
.bub strong{color:var(--gold);font-weight:600}
.bub em{color:#8db4d8;font-style:italic}
.bub pre{background:#060e1c;border:1px solid var(--bd);border-radius:7px;padding:11px;margin:9px 0;overflow-x:auto;font-family:'JetBrains Mono',monospace;font-size:11.5px;color:#93c5fd}
.bub code{font-family:'JetBrains Mono',monospace;font-size:11.5px;background:rgba(255,255,255,.06);padding:1px 5px;border-radius:4px}
.bub ul,.bub ol{padding-left:17px;margin:5px 0}
.bub li{margin-bottom:3px}
.bub p{margin-bottom:6px}

/* Actions */
.acts{display:flex;gap:6px;margin-top:9px;flex-wrap:wrap}
.ab{font-size:11px;padding:4px 11px;border-radius:6px;border:1px solid var(--bd);background:var(--s1);color:var(--txd);cursor:pointer;transition:all .16s;display:flex;align-items:center;gap:4px;font-family:'DM Sans',sans-serif}
.ab:hover{border-color:var(--gdim);color:var(--gold)}
.ab.hi{border-color:rgba(201,168,76,.35);color:var(--gold)}

/* Typing */
.typing{display:flex;align-items:center;gap:4px;padding:11px 15px;background:var(--s2);border:1px solid var(--bd);border-radius:11px;border-top-left-radius:3px;width:fit-content}
.typing span{width:5px;height:5px;border-radius:50%;background:var(--gdim);animation:bounce 1.1s infinite}
.typing span:nth-child(2){animation-delay:.18s}
.typing span:nth-child(3){animation-delay:.36s}

/* Input */
.ia{padding:13px 18px 16px;background:var(--s1);border-top:1px solid var(--bd);flex-shrink:0}
.tb{display:flex;gap:6px;margin-bottom:9px;flex-wrap:wrap}
.tbtn{display:flex;align-items:center;gap:5px;padding:4px 11px;border-radius:6px;border:1px solid var(--bd);background:var(--s2);color:var(--txd);font-size:11.5px;cursor:pointer;transition:all .16s;font-family:'DM Sans',sans-serif}
.tbtn:hover{border-color:var(--gdim);color:var(--gold)}
.ir{display:flex;gap:9px;align-items:flex-end}
.iw{flex:1;background:var(--s2);border:1px solid var(--bd);border-radius:9px;padding:9px 13px;display:flex;align-items:flex-end;gap:7px;transition:all .16s}
.iw:focus-within{border-color:var(--gdim);box-shadow:0 0 0 3px var(--gg)}
textarea{flex:1;background:none;border:none;outline:none;color:var(--tx);font-family:'DM Sans',sans-serif;font-size:13.5px;resize:none;max-height:110px;line-height:1.5}
textarea::placeholder{color:var(--txd)}
.sb-btn{width:38px;height:38px;border-radius:8px;background:linear-gradient(135deg,var(--gdim),var(--gold));border:none;color:#08101e;font-size:15px;cursor:pointer;flex-shrink:0;transition:all .16s;display:flex;align-items:center;justify-content:center;font-weight:700}
.sb-btn:hover{transform:scale(1.06)}
.sb-btn:disabled{opacity:.35;cursor:not-allowed;transform:none}

/* Modals */
.ov{position:fixed;inset:0;background:rgba(0,0,0,.72);backdrop-filter:blur(5px);z-index:200;display:none;align-items:center;justify-content:center}
.ov.open{display:flex;animation:fi .2s ease}
.modal{background:var(--s1);border:1px solid var(--bd);border-radius:14px;padding:26px;width:90%;max-width:460px;animation:su .28s ease}
.modal h3{font-family:'Playfair Display',serif;font-size:17px;color:var(--gold);margin-bottom:15px}
.fld{margin-bottom:13px}
.fld label{display:block;font-size:10px;text-transform:uppercase;letter-spacing:1px;color:var(--txd);margin-bottom:5px}
.fld input,.fld textarea{width:100%;background:var(--s2);border:1px solid var(--bd);border-radius:7px;padding:9px 12px;color:var(--tx);font-family:'DM Sans',sans-serif;font-size:13px;outline:none;transition:border-color .15s}
.fld input:focus,.fld textarea:focus{border-color:var(--gdim)}
.fld textarea{min-height:95px;resize:vertical}
.mf{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}
.btn{padding:8px 18px;border-radius:7px;font-family:'DM Sans',sans-serif;font-size:13px;font-weight:500;cursor:pointer;border:none;transition:all .16s}
.bg{background:var(--s2);color:var(--txd);border:1px solid var(--bd)}
.bg:hover{color:var(--tx)}
.bgo{background:linear-gradient(135deg,var(--gdim),var(--gold));color:#08101e;font-weight:700}
.bgo:hover{transform:translateY(-1px)}

/* Upload zone */
.uz{border:2px dashed var(--bd);border-radius:9px;padding:26px;text-align:center;cursor:pointer;transition:all .16s;margin-bottom:12px}
.uz:hover{border-color:var(--gdim);background:var(--gg)}
.uz p{color:var(--txd);font-size:12.5px;margin-top:7px}

/* Toast */
.toast{position:fixed;bottom:22px;right:22px;background:var(--s2);border:1px solid var(--bd);border-radius:9px;padding:11px 16px;font-size:13px;color:var(--tx);z-index:300;animation:sr .25s ease;display:flex;align-items:center;gap:7px}
.toast.ok{border-color:var(--green)}
.toast.err{border-color:var(--red)}

/* Animations */
@keyframes fu{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
@keyframes fi{from{opacity:0}to{opacity:1}}
@keyframes su{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}
@keyframes sr{from{opacity:0;transform:translateX(16px)}to{opacity:1;transform:translateX(0)}}
@keyframes bounce{0%,80%,100%{transform:scale(.55)}40%{transform:scale(1)}}
@media(max-width:620px){.sb{display:none}.bub{max-width:88%}.tb{display:none}}
</style>
</head>
<body>

<!-- Sidebar -->
<aside class="sb">
  <div class="logo">
    <div class="logo-m">MARK4K</div>
    <div class="logo-s">Academic Assistant</div>
  </div>
  <nav class="nav">
    <div class="ns">Modes</div>
    <div class="ni on" onclick="setMode('chat',this)"><span>💬</span>Chat Advisor</div>
    <div class="ni" onclick="setMode('path',this)"><span>🎓</span>Education Path</div>
    <div class="ni" onclick="setMode('pdf',this)"><span>📄</span>PDF Analyzer</div>
    <div class="ni" onclick="setMode('code',this)"><span>💻</span>Code Generator</div>
    <div class="ni" onclick="setMode('email',this)"><span>📧</span>Email Drafter</div>
  </nav>
  <div class="sf">
    <div class="do-p">⚡ DigitalOcean Gradient AI</div>
    <div style="margin-top:6px">Qwen3 32B · Agent Platform</div>
  </div>
</aside>

<!-- Main -->
<div class="main">
  <div class="topbar">
    <div class="tl">
      <span class="ttl" id="ttl">Project Advisor</span>
      <span class="mbadge" id="mbadge">Chat Mode</span>
    </div>
    <div class="tr">
      <button class="ib" title="Clear chat" onclick="clearChat()">🗑</button>
      <button class="ib" title="New session" onclick="newSession()">✦</button>
    </div>
  </div>

  <div class="chat" id="chat">
    <div class="wl" id="wl">
      <span class="wg">🎓</span>
      <h2>Hello, I'm Mark4k</h2>
      <p>Your AI-powered academic assistant. I help with school projects, career paths, document analysis, and code generation — all powered by DigitalOcean Gradient AI.</p>
      <div class="chips">
        <div class="chip" onclick="sug('Help me pick a science project topic for secondary school')">🔬 Science project idea</div>
        <div class="chip" onclick="sug('What is the best path from BSc Computer Science to becoming a professor?')">🎓 Career path advice</div>
        <div class="chip" onclick="sug('Generate a Flask app for a student grade tracker project')">💻 Generate Flask app</div>
        <div class="chip" onclick="sug('Draft a professional email to my lecturer requesting an assignment extension')">📧 Draft email</div>
        <div class="chip" onclick="sug('What scholarships are available for a Nigerian BSc graduate applying for Masters abroad?')">🌍 Scholarship info</div>
        <div class="chip" onclick="sug('I need a creative and unique history project idea for my final year')">📚 History project</div>
      </div>
    </div>
  </div>

  <div class="ia">
    <div class="tb">
      <button class="tbtn" onclick="openPDF()">📎 Attach PDF</button>
      <button class="tbtn" onclick="qEmail()">📧 Draft Email</button>
      <button class="tbtn" onclick="qCode()">💻 Gen Code</button>
      <button class="tbtn" onclick="qPath()">🎓 Career Path</button>
    </div>
    <div class="ir">
      <div class="iw">
        <textarea id="inp" rows="1" placeholder="Ask Mark4k anything about your studies…"
          onkeydown="handleKey(event)" oninput="grow(this)"></textarea>
      </div>
      <button class="sb-btn" id="sendBtn" onclick="send()">➤</button>
    </div>
  </div>
</div>

<!-- PDF Modal -->
<div class="ov" id="pdfOv" onclick="closeOv('pdfOv')">
  <div class="modal" onclick="event.stopPropagation()">
    <h3>📄 Analyze a PDF</h3>
    <div class="uz" onclick="document.getElementById('pdfIn').click()">
      <div style="font-size:30px">📂</div>
      <p>Click to upload — assignment, syllabus, exam paper, textbook chapter…</p>
      <input type="file" id="pdfIn" accept=".pdf" style="display:none" onchange="onPDF(this)">
    </div>
    <div id="pdfName" style="font-size:11.5px;color:var(--gold);margin-bottom:10px"></div>
    <div class="fld">
      <label>What should Mark4k do with this document?</label>
      <textarea id="pdfQ">Analyze this document, summarize the key requirements, and help me plan my approach.</textarea>
    </div>
    <div class="mf">
      <button class="btn bg" onclick="closeOv('pdfOv')">Cancel</button>
      <button class="btn bgo" onclick="submitPDF()">Analyze →</button>
    </div>
  </div>
</div>

<!-- Email Modal -->
<div class="ov" id="emailOv" onclick="closeOv('emailOv')">
  <div class="modal" onclick="event.stopPropagation()">
    <h3>📧 Send Email</h3>
    <div class="fld"><label>To (recipient email)</label><input type="email" id="eTo" placeholder="professor@university.edu"></div>
    <div class="fld"><label>Subject</label><input type="text" id="eSub" placeholder="Email subject line"></div>
    <div class="fld"><label>Message body</label><textarea id="eBody" style="min-height:110px" placeholder="Email body — Mark4k can draft this for you first…"></textarea></div>
    <div class="fld"><label>Your Gmail address</label><input type="email" id="eSender" placeholder="you@gmail.com"></div>
    <div class="fld">
      <label>Gmail App Password <span style="color:var(--txd);text-transform:none;font-size:10px">(myaccount.google.com/apppasswords)</span></label>
      <input type="password" id="ePass" placeholder="16-character app password">
    </div>
    <div class="mf">
      <button class="btn bg" onclick="closeOv('emailOv')">Cancel</button>
      <button class="btn bgo" onclick="doEmail()">Send Email →</button>
    </div>
  </div>
</div>

<script>
let mode='chat', pdfFile=null;
const modes={
  chat:{t:'Project Advisor',b:'Chat Mode'},
  path:{t:'Education Path',b:'Career Mode'},
  pdf: {t:'PDF Analyzer',b:'Document Mode'},
  code:{t:'Code Generator',b:'Code Mode'},
  email:{t:'Email Drafter',b:'Email Mode'},
};
const hints={
  chat:'Ask me about school projects, subjects, or assignments…',
  path:'Tell me your current level and field of interest…',
  pdf:'Attach a PDF and I\'ll analyze it for you…',
  code:'Describe the app or script you want me to generate…',
  email:'Tell me who to write to and what the email should say…',
};

function setMode(m,el){
  mode=m;
  document.querySelectorAll('.ni').forEach(i=>i.classList.remove('on'));
  if(el) el.classList.add('on');
  document.getElementById('ttl').textContent=modes[m].t;
  document.getElementById('mbadge').textContent=modes[m].b;
  document.getElementById('inp').placeholder=hints[m];
  if(m==='pdf') openPDF();
}

function grow(el){ el.style.height='auto'; el.style.height=Math.min(el.scrollHeight,110)+'px'; }
function handleKey(e){ if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();} }
function sug(t){ document.getElementById('inp').value=t; send(); }
function qEmail(){ document.getElementById('inp').value='Draft a professional email to my lecturer about my project progress.'; mode='email'; send(); }
function qCode(){  document.getElementById('inp').value='Generate a complete Flask web app for my school project.'; mode='code'; send(); }
function qPath(){  document.getElementById('inp').value='What academic options do I have after completing my current degree?'; mode='path'; send(); }
function openPDF(){ document.getElementById('pdfOv').classList.add('open'); }
function closeOv(id){ document.getElementById(id).classList.remove('open'); }

async function send(){
  const el=document.getElementById('inp'), txt=el.value.trim();
  if(!txt) return;
  hideWl(); addMsg('u',txt);
  el.value=''; el.style.height='auto';
  const ty=addTyping();
  document.getElementById('sendBtn').disabled=true;
  try{
    const r=await fetch('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:txt,mode})});
    const d=await r.json(); ty.remove();
    if(d.error){ addMsg('a','⚠️ '+d.error); }
    else{ const w=addMsg('a',d.reply); addActs(w,d); }
  }catch(e){ ty.remove(); addMsg('a','⚠️ Connection error. Please try again.'); }
  document.getElementById('sendBtn').disabled=false;
}

function addMsg(role,text){
  const w=document.createElement('div'); w.className='msg '+role;
  const av=document.createElement('div'); av.className='av '+role; av.textContent=role==='a'?'🎓':'👤';
  const b=document.createElement('div'); b.className='bub'; b.innerHTML=mdRender(text);
  if(role==='a'){w.append(av,b);}else{w.append(b,av);}
  document.getElementById('chat').appendChild(w);
  w.scrollIntoView({behavior:'smooth',block:'end'});
  return w;
}

function addActs(w,d){
  const b=w.querySelector('.bub');
  const acts=document.createElement('div'); acts.className='acts';
  // PDF download
  const pb=document.createElement('button'); pb.className='ab hi'; pb.innerHTML='📥 Save as PDF';
  pb.onclick=()=>dlPDF(d.reply); acts.appendChild(pb);
  // ZIP if code detected
  if(d.code_blocks&&d.code_blocks.length>0){
    const zb=document.createElement('button'); zb.className='ab hi'; zb.innerHTML='📦 Download ZIP';
    zb.onclick=()=>dlZip(d.code_blocks); acts.appendChild(zb);
  }
  // Email
  const eb=document.createElement('button'); eb.className='ab'; eb.innerHTML='📧 Email this';
  eb.onclick=()=>prefillEmail(d.reply); acts.appendChild(eb);
  b.appendChild(acts);
}

function addTyping(){
  const w=document.createElement('div'); w.className='msg a';
  w.innerHTML='<div class="av a">🎓</div><div class="typing"><span></span><span></span><span></span></div>';
  document.getElementById('chat').appendChild(w);
  w.scrollIntoView({behavior:'smooth',block:'end'});
  return w;
}

function hideWl(){ const w=document.getElementById('wl'); if(w) w.remove(); }

async function dlPDF(content){
  try{
    const r=await fetch('/download-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Mark4k — Project Plan',content})});
    if(!r.ok){toast('PDF failed — install fpdf2','err');return;}
    const blob=await r.blob(), url=URL.createObjectURL(blob);
    Object.assign(document.createElement('a'),{href:url,download:'mark4k-plan.pdf'}).click();
    URL.revokeObjectURL(url); toast('📥 PDF downloaded!','ok');
  }catch{toast('PDF download failed','err');}
}

async function dlZip(blocks){
  try{
    const r=await fetch('/download-zip',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code_blocks:blocks})});
    if(!r.ok){toast('ZIP failed','err');return;}
    const blob=await r.blob(), url=URL.createObjectURL(blob);
    Object.assign(document.createElement('a'),{href:url,download:'mark4k-project.zip'}).click();
    URL.revokeObjectURL(url); toast('📦 ZIP downloaded!','ok');
  }catch{toast('ZIP download failed','err');}
}

function onPDF(input){
  pdfFile=input.files[0];
  document.getElementById('pdfName').textContent=pdfFile?'📎 '+pdfFile.name:'';
}

async function submitPDF(){
  if(!pdfFile){toast('Please select a PDF','err');return;}
  const q=document.getElementById('pdfQ').value.trim()||'Analyze this document.';
  closeOv('pdfOv'); hideWl();
  addMsg('u','📎 Uploaded: '+pdfFile.name+'\n\n'+q);
  const ty=addTyping();
  const fd=new FormData(); fd.append('file',pdfFile); fd.append('question',q);
  try{
    const r=await fetch('/analyze-pdf',{method:'POST',body:fd});
    const d=await r.json(); ty.remove();
    const w=addMsg('a',d.reply||d.error);
    if(d.reply) addActs(w,d);
  }catch{ ty.remove(); addMsg('a','⚠️ Could not analyze PDF. Make sure pypdf is installed.'); }
}

function prefillEmail(content){
  const sm=content.match(/Subject[:\s]+(.+)/i);
  document.getElementById('eSub').value=sm?sm[1].trim():'Academic Inquiry';
  document.getElementById('eBody').value=content.replace(/\*\*/g,'').replace(/\*/g,'').replace(/#{1,6}\s/g,'');
  document.getElementById('emailOv').classList.add('open');
}

async function doEmail(){
  const to=document.getElementById('eTo').value.trim();
  const sub=document.getElementById('eSub').value.trim();
  const body=document.getElementById('eBody').value.trim();
  const from=document.getElementById('eSender').value.trim();
  const pass=document.getElementById('ePass').value;
  if(!to||!sub||!body||!from||!pass){toast('Please fill all fields','err');return;}
  try{
    const r=await fetch('/send-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to,subject:sub,body,sender:from,password:pass})});
    const d=await r.json();
    if(d.success){ closeOv('emailOv'); toast('📧 Email sent!','ok'); addMsg('a','Email sent to **'+to+'** — Subject: *'+sub+'*'); }
    else{ toast(d.error||'Email failed','err'); }
  }catch{ toast('Email send failed','err'); }
}

function clearChat(){ document.getElementById('chat').innerHTML=''; fetch('/clear-session',{method:'POST'}); }
function newSession(){
  clearChat();
  const w=document.createElement('div'); w.className='wl'; w.id='wl';
  w.innerHTML='<span class="wg">🎓</span><h2>New Session</h2><p>Start a fresh conversation with Mark4k.</p>';
  document.getElementById('chat').appendChild(w);
}

function toast(msg,type){
  const t=document.createElement('div'); t.className='toast '+(type||''); t.textContent=msg;
  document.body.appendChild(t); setTimeout(()=>t.remove(),3000);
}

// Minimal markdown-to-HTML renderer
function mdRender(t){
  return t
    .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    .replace(/```(\w*)\n([\s\S]*?)```/g,(_,l,c)=>'<pre><code>'+c.trim()+'</code></pre>')
    .replace(/`([^`]+)`/g,'<code>$1</code>')
    .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,'<em>$1</em>')
    .replace(/^#{1,3}\s+(.+)$/gm,'<strong>$1</strong>')
    .replace(/^\s*[-*]\s+(.+)$/gm,'<li>$1</li>')
    .replace(/(<li>[\s\S]+?<\/li>)/g,'<ul>$1</ul>')
    .replace(/\n\n/g,'<br><br>').replace(/\n/g,'<br>');
}
</script>
</body>
</html>"""


# ══════════════════════════════════════════════════════════════════════
#  ROUTES
# ══════════════════════════════════════════════════════════════════════

@app.route("/")
def index():
    """Serve the embedded single-page frontend."""
    return render_template_string(HTML)


@app.route("/chat", methods=["POST"])
def chat():
    """
    Core chat endpoint — sends messages to DigitalOcean Gradient AI.
    Maintains multi-turn history in Flask session.
    Returns reply + extracted code blocks for ZIP download.
    """
    data    = request.get_json()
    message = data.get("message", "").strip()
    mode    = data.get("mode", "chat")

    if not message:
        return jsonify({"error": "Empty message"}), 400

    history = session.get("history", [])

    # Prepend mode context hint so agent knows which feature is active
    mode_hint = MODE_PROMPTS.get(mode, "")
    full_msg  = f"[{mode_hint}]\n\n{message}" if mode_hint else message
    history.append({"role": "user", "content": full_msg})

    # Trim to prevent session overflow
    if len(history) > MAX_HISTORY:
        history = history[-MAX_HISTORY:]

    try:
        reply = call_agent(history)
    except Exception as e:
        return jsonify({"error": f"Agent error: {str(e)}"}), 500

    # Store clean message (without hint) in history
    history[-1]["content"] = message
    history.append({"role": "assistant", "content": reply})
    session["history"] = history[-MAX_HISTORY:]

    return jsonify({"reply": reply, "code_blocks": extract_code_blocks(reply)})


@app.route("/analyze-pdf", methods=["POST"])
def analyze_pdf():
    """
    Accept PDF upload, extract text via pypdf, send to agent for analysis.
    pip install pypdf
    """
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400
    if not PYPDF_ENABLED:
        return jsonify({"error": "pypdf not installed. Run: pip install pypdf"}), 500

    pdf_file = request.files["file"]
    question = request.form.get("question", "Analyze this document.")

    try:
        reader   = pypdf.PdfReader(io.BytesIO(pdf_file.read()))
        pdf_text = "\n".join(p.extract_text() or "" for p in reader.pages)
        pdf_text = pdf_text[:6000]  # cap to avoid token overflow
    except Exception as e:
        return jsonify({"error": f"Could not read PDF: {str(e)}"}), 400

    prompt = (
        f"The student has uploaded a PDF document. Extracted content:\n\n---\n"
        f"{pdf_text}\n---\n\nStudent's request: {question}\n\n"
        f"Please analyze the document and respond helpfully."
    )

    try:
        reply = call_agent([{"role": "user", "content": prompt}])
    except Exception as e:
        return jsonify({"error": f"Agent error: {str(e)}"}), 500

    return jsonify({"reply": reply, "code_blocks": extract_code_blocks(reply)})


@app.route("/download-zip", methods=["POST"])
def download_zip():
    """Package agent-generated code blocks into a ZIP file."""
    data        = request.get_json()
    code_blocks = data.get("code_blocks", [])
    if not code_blocks:
        return jsonify({"error": "No code blocks"}), 400
    return send_file(build_zip(code_blocks), mimetype="application/zip",
                     as_attachment=True, download_name="mark4k-project.zip")


@app.route("/download-plan", methods=["POST"])
def download_plan():
    """Generate a branded PDF of the agent's response for the student."""
    if not PDF_ENABLED:
        return jsonify({"error": "fpdf2 not installed. Run: pip install fpdf2"}), 500
    data = request.get_json()
    try:
        buf = generate_pdf(data.get("title", "Project Plan"), data.get("content", ""))
        return send_file(buf, mimetype="application/pdf",
                         as_attachment=True, download_name="mark4k-plan.pdf")
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/send-email", methods=["POST"])
def send_email_route():
    """
    Send an academic email via Gmail SMTP.
    Requires a Gmail App Password — NOT the main Gmail password.
    Generate one at: https://myaccount.google.com/apppasswords
    """
    data     = request.get_json()
    to       = data.get("to")
    subject  = data.get("subject")
    body     = data.get("body")
    sender   = data.get("sender")
    password = data.get("password")

    if not all([to, subject, body, sender, password]):
        return jsonify({"error": "All fields are required"}), 400

    try:
        msg = MIMEMultipart()
        msg["From"] = sender; msg["To"] = to; msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as srv:
            srv.login(sender, password)
            srv.sendmail(sender, to, msg.as_string())
        return jsonify({"success": True})
    except smtplib.SMTPAuthenticationError:
        return jsonify({"error": "Gmail auth failed. Use an App Password from myaccount.google.com/apppasswords"}), 400
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/clear-session", methods=["POST"])
def clear_session():
    """Reset the conversation history in the session."""
    session.pop("history", None)
    return jsonify({"success": True})


# ══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    print("\n🎓  Mark4k Academic Assistant")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("   http://localhost:5000")
    print("   Powered by DigitalOcean Gradient AI")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")
    app.run(debug=True)